name: DIGITALOCEAN_DEPLOY

on: 
  push: 
    branches: [ main ]
      
jobs: 
  build: 
    runs-on: self-hosted
      
    steps: 
      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id

      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}

      - uses: actions/checkout@main
      - name: Create .env on root server 
        run: | 
          echo ${{ secrets.ENV_ROOT }} >> .env 
          echo 'ce fichier doit fonctionner'
        
      - name: Create .env on bedrock root
        working-directory: ./src
        run: echo ${{ secrets.ENV_BEDROCK }} > .env 
          
      - name: Run composer create-project
        run: docker-compose run composer create-project 
        
      - name: Run docker compose 
        run: docker-compose up -d 
      
          
      
